## move with pandas

In [2]:
import numpy as np 
import pandas as pd

In [3]:
labels = ['a','b','c']
my_list =[10,20,30]
arr = np.array([10,20,30])
d = {'a':10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=d)

a    10
2    20
3    30
dtype: int64

In [6]:
pd.Series(d)

a    10
2    20
3    30
dtype: int64

### Data Frame

In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age':[45,56,25,65,33],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [70000, 85000, 62000, 95000, 78000]
}
index = ['a','b','c','d','e']
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
 'Age': [45, 56, 25, 65, 33],
 'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
 'Salary': [70000, 85000, 62000, 95000, 78000]}

In [8]:
df = pd.DataFrame(data,index=index)

In [9]:
df

      Name  Age      City  Salary
a    Alice   45  New York   70000
b      Bob   56    London   85000
c  Charlie   25     Paris   62000
d    David   65     Tokyo   95000
e      Eva   33    Sydney   78000

In [10]:
pd

In [11]:
people_list = [
    # [Name, Age, City, Salary]
    ['Alice', 25, 'New York', 70000],
    ['Bob', 30, 'London', 85000],
    ['Charlie', 35, 'Paris', 95000],
    ['David', 40, 'Tokyo', 110000],
    ['Eva', 28, 'Sydney', 78000]
]
index = [1,2,3,4,5]
coloum_list = ["Name","Age","City","Salary"]
df2 =pd.DataFrame(people_list,columns=coloum_list,index= index)
print(df2)

      Name  Age      City  Salary
1    Alice   25  New York   70000
2      Bob   30    London   85000
3  Charlie   35     Paris   95000
4    David   40     Tokyo  110000
5      Eva   28    Sydney   78000

In [12]:
df2['Name']

1      Alice
2        Bob
3    Charlie
4      David
5        Eva
Name: Name, dtype: str

In [13]:
df2[['Name',"City"]]

      Name      City
1    Alice  New York
2      Bob    London
3  Charlie     Paris
4    David     Tokyo
5      Eva    Sydney

In [14]:
df2['Designation']= ["Doctor","Engineer","Barber","Salesman","IAS"]
df2.drop("Designation",axis=1,inplace= True)
df2.drop(['City','Salary'] ,axis=1,inplace=False)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   35
4    David   40
5      Eva   28

In [15]:
df2

      Name  Age      City  Salary
1    Alice   25  New York   70000
2      Bob   30    London   85000
3  Charlie   35     Paris   95000
4    David   40     Tokyo  110000
5      Eva   28    Sydney   78000

In [16]:
df2.loc[[1,2]]

    Name  Age      City  Salary
1  Alice   25  New York   70000
2    Bob   30    London   85000

In [17]:
df2.loc[[4,5]][['Name','Age']]

    Name  Age
4  David   40
5    Eva   28

In [18]:
df2.loc[[1,2]][['City','Salary']]

       City  Salary
1  New York   70000
2    London   85000

In [19]:
df2

      Name  Age      City  Salary
1    Alice   25  New York   70000
2      Bob   30    London   85000
3  Charlie   35     Paris   95000
4    David   40     Tokyo  110000
5      Eva   28    Sydney   78000

In [20]:
df2['Name'][(df2['Age']>=30)&(df2['City']=="Tokyo")]

4    David
Name: Name, dtype: str

In [21]:
data = {
    "Name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Eva",
        "Frank",
        "Grace",
        "Henry",
    ],
    "Age": [25, np.nan, 35, 40, 28, 45, np.nan, 50],
    "City": [
        "New York",
        "London",
        None,
        "Tokyo",
        "Sydney",
        "New York",
        "Paris",
        None,
    ],
    "Salary": [70000, 85000, 95000, np.nan, 78000, 105000, np.nan, 120000],
}
index = [1, 2, 3, 4, 5, 6, 7, 8]
df3 =pd.DataFrame(data,index=index)

In [22]:
df3

      Name   Age      City    Salary
1    Alice  25.0  New York   70000.0
2      Bob   NaN    London   85000.0
3  Charlie  35.0       NaN   95000.0
4    David  40.0     Tokyo       NaN
5      Eva  28.0    Sydney   78000.0
6    Frank  45.0  New York  105000.0
7    Grace   NaN     Paris       NaN
8    Henry  50.0       NaN  120000.0

In [23]:
df3.isna()

    Name    Age   City  Salary
1  False  False  False   False
2  False   True  False   False
3  False  False   True   False
4  False  False  False    True
5  False  False  False   False
6  False  False  False   False
7  False   True  False    True
8  False  False   True   False

In [24]:
df3.isna()

    Name    Age   City  Salary
1  False  False  False   False
2  False   True  False   False
3  False  False   True   False
4  False  False  False    True
5  False  False  False   False
6  False  False  False   False
7  False   True  False    True
8  False  False   True   False

In [25]:
df3.isna().sum()

Name      0
Age       2
City      2
Salary    2
dtype: int64

In [26]:
df3.isna().any()

Name      False
Age        True
City       True
Salary     True
dtype: bool

In [27]:
df3

      Name   Age      City    Salary
1    Alice  25.0  New York   70000.0
2      Bob   NaN    London   85000.0
3  Charlie  35.0       NaN   95000.0
4    David  40.0     Tokyo       NaN
5      Eva  28.0    Sydney   78000.0
6    Frank  45.0  New York  105000.0
7    Grace   NaN     Paris       NaN
8    Henry  50.0       NaN  120000.0

In [28]:
df3.dropna()

    Name   Age      City    Salary
1  Alice  25.0  New York   70000.0
5    Eva  28.0    Sydney   78000.0
6  Frank  45.0  New York  105000.0

In [29]:
df3

      Name   Age      City    Salary
1    Alice  25.0  New York   70000.0
2      Bob   NaN    London   85000.0
3  Charlie  35.0       NaN   95000.0
4    David  40.0     Tokyo       NaN
5      Eva  28.0    Sydney   78000.0
6    Frank  45.0  New York  105000.0
7    Grace   NaN     Paris       NaN
8    Henry  50.0       NaN  120000.0

In [30]:
df3.dropna(thresh=4)

    Name   Age      City    Salary
1  Alice  25.0  New York   70000.0
5    Eva  28.0    Sydney   78000.0
6  Frank  45.0  New York  105000.0

In [31]:
df3

      Name   Age      City    Salary
1    Alice  25.0  New York   70000.0
2      Bob   NaN    London   85000.0
3  Charlie  35.0       NaN   95000.0
4    David  40.0     Tokyo       NaN
5      Eva  28.0    Sydney   78000.0
6    Frank  45.0  New York  105000.0
7    Grace   NaN     Paris       NaN
8    Henry  50.0       NaN  120000.0

In [32]:
df3.fillna(5)

      Name   Age      City    Salary
1    Alice  25.0  New York   70000.0
2      Bob   5.0    London   85000.0
3  Charlie  35.0         5   95000.0
4    David  40.0     Tokyo       5.0
5      Eva  28.0    Sydney   78000.0
6    Frank  45.0  New York  105000.0
7    Grace   5.0     Paris       5.0
8    Henry  50.0         5  120000.0

In [33]:
values = {'Name':'Guest',"Age":df3['Age'].sum()/2,"City":"India","Salary":df3['Salary'].sum()/2}

df3.fillna(value =values)

      Name    Age      City    Salary
1    Alice   25.0  New York   70000.0
2      Bob  111.5    London   85000.0
3  Charlie   35.0     India   95000.0
4    David   40.0     Tokyo  276500.0
5      Eva   28.0    Sydney   78000.0
6    Frank   45.0  New York  105000.0
7    Grace  111.5     Paris  276500.0
8    Henry   50.0     India  120000.0

In [ ]:
it_data = {
    "Emp_ID":[1,2,3,4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Salary":[5000, 95000, 78000, 10500]
}


# DataFrame 2: HR Department (4 rows)
hr_data = {
    "Emp_ID":[1,2,3,8],
    "Name": ["Eva", "Frank", "Grace", "Henry"],
    "Salary":[50050, 950500, 782000, 120500],
}
hr =pd.DataFrame(hr_data)
it =pd.DataFrame(it_data)

In [46]:
pd.merge(it,hr,on="Emp_ID")

   Emp_ID   Name_x  Salary_x Name_y  Salary_y
0       1    Alice      5000    Eva     50050
1       2      Bob     95000  Frank    950500
2       3  Charlie     78000  Grace    782000

In [47]:
pd.merge(it,hr,on="Emp_ID",how ="inner")

   Emp_ID   Name_x  Salary_x Name_y  Salary_y
0       1    Alice      5000    Eva     50050
1       2      Bob     95000  Frank    950500
2       3  Charlie     78000  Grace    782000

In [48]:
pd.merge(it,hr,on="Emp_ID",how="outer")

   Emp_ID   Name_x  Salary_x Name_y  Salary_y
0       1    Alice    5000.0    Eva   50050.0
1       2      Bob   95000.0  Frank  950500.0
2       3  Charlie   78000.0  Grace  782000.0
3       4    David   10500.0    NaN       NaN
4       8      NaN       NaN  Henry  120500.0

In [49]:
hr

   Emp_ID   Name  Salary
0       1    Eva   50050
1       2  Frank  950500
2       3  Grace  782000
3       8  Henry  120500

In [50]:
it

   Emp_ID     Name  Salary
0       1    Alice    5000
1       2      Bob   95000
2       3  Charlie   78000
3       4    David   10500

In [51]:
pd.merge(it,hr,on="Emp_ID",how="left")

   Emp_ID   Name_x  Salary_x Name_y  Salary_y
0       1    Alice      5000    Eva   50050.0
1       2      Bob     95000  Frank  950500.0
2       3  Charlie     78000  Grace  782000.0
3       4    David     10500    NaN       NaN

In [52]:
pd.merge(it,hr,on="Emp_ID",how="right")

   Emp_ID   Name_x  Salary_x Name_y  Salary_y
0       1    Alice    5000.0    Eva     50050
1       2      Bob   95000.0  Frank    950500
2       3  Charlie   78000.0  Grace    782000
3       8      NaN       NaN  Henry    120500

In [72]:
# Define df1
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

df1
# Define df2
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [74]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [75]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [76]:
pd.concat([df1,df2])

    A   B   C    D
0  A0  B0  C0   D0
1  A1  B1  C1   D1
2  A2  B2  C2   D2
0  A3  B3  C3  NaN
1  A4  B4  C4  NaN
2  A5  B5  C5  NaN

In [77]:
pd.concat([df1,df2],axis =1)

    A   B   C   D   A   B   C
0  A0  B0  C0  D0  A3  B3  C3
1  A1  B1  C1  D1  A4  B4  C4
2  A2  B2  C2  D2  A5  B5  C5

In [84]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df6 =pd.DataFrame(data)

In [85]:
df6

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [96]:
cat =df6.groupby('Category')
cat
for i , v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [97]:
cat = df6.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [100]:
cat = df6.groupby(['Category','Store'])['Sales'].mean()
cat

Category  Store
A         S1       110.0
          S2       175.0
B         S1       250.0
          S2       215.0
Name: Sales, dtype: float64

In [103]:
df6['Sales'].agg(['mean'])

mean    187.5
Name: Sales, dtype: float64

# Pivot Table

In [106]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

# Create the DataFrame
df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    121     52   John
1  2023-01-02       B   West    246     43   Mary
2  2023-01-03       C  North    774     57    Bob
3  2023-01-04       D  South    417     47  Alice
4  2023-01-05       A   East    663     72   John
5  2023-01-06       B   West    843     38   Mary
6  2023-01-07       C  North    274     77    Bob
7  2023-01-08       D  South    137     66  Alice
8  2023-01-09       A   East    683     43   John
9  2023-01-10       B   West    340     83   Mary
10 2023-01-11       C  North    566     27    Bob
11 2023-01-12       D  South    121     46  Alice
12 2023-01-13       A   East    121     79   John
13 2023-01-14       B   West    430     22   Mary
14 2023-01-15       C  North    740     33    Bob
15 2023-01-16       D  South    725     71  Alice
16 2023-01-17       A   East    711     67   John
17 2023-01-18       B   West    383     54   Mary
18 2023-01-19       C  North    433     88    Bob
19 2023-01-20       D  South    893     15  Alice

In [112]:
region =df.groupby('Region')['Sales']
region
for i ,v in region:
    print(i)
    print(v)

East
0     121
4     663
8     683
12    121
16    711
Name: Sales, dtype: int32
North
2     774
6     274
10    566
14    740
18    433
Name: Sales, dtype: int32
South
3     417
7     137
11    121
15    725
19    893
Name: Sales, dtype: int32
West
1     246
5     843
9     340
13    430
17    383
Name: Sales, dtype: int32

In [ ]:
table =pd.pivot_table(df,values='Sales',index = 'Region',columns='Product')
table

Product      A      B      C      D
Region
East     459.8    NaN    NaN    NaN
North      NaN    NaN  557.4    NaN
South      NaN    NaN    NaN  458.6
West       NaN  448.4    NaN    NaN

In [124]:
res = table.fillna(0)
res

Product      A      B      C      D
Region
East     459.8    0.0    0.0    0.0
North      0.0    0.0  557.4    0.0
South      0.0    0.0    0.0  458.6
West       0.0  448.4    0.0    0.0

In [129]:
table =pd.pivot_table(df,values=['Sales','Units'],index = ['Region','Rep'],columns='Product')
table

              Sales                      Units
Product           A      B      C      D     A     B     C     D
Region Rep
East   John   459.8    NaN    NaN    NaN  62.6   NaN   NaN   NaN
North  Bob      NaN    NaN  557.4    NaN   NaN   NaN  56.4   NaN
South  Alice    NaN    NaN    NaN  458.6   NaN   NaN   NaN  49.0
West   Mary     NaN  448.4    NaN    NaN   NaN  48.0   NaN   NaN

## Cross Tab

In [131]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [139]:
data =pd.read_csv(r'anime.csv')

In [140]:
data.describe

<bound method NDFrame.describe of     Rank                                        Title  Score/Rating
0      1                Frieren: Beyond Journey's End          9.30
1      2             Fullmetal Alchemist: Brotherhood          9.10
2      3                                  Steins;Gate          9.07
3      4                                     Gintama°          9.06
4      5                       Hunter x Hunter (2011)          9.04
5      6                     Fruits Basket: The Final          8.99
6      7              Bleach: Thousand-Year Blood War          8.99
7      8                           Gintama: The Final          8.98
8      9                         Clannad: After Story          8.95
9     10      Code Geass: Lelouch of the Rebellion R2          8.91
10    11                               A Silent Voice          8.89
11    12                                      Monster          8.88
12    13                                   Your Name.          8.84
13    14                                Spirited Away          8.78
14    15  Shingeki no Kyojin: The Final Season Part 2          8.76
15    16                                 Vinland Saga          8.76
16    17                             Bocchi the Rock!          8.76
17    18                                 Cowboy Bebop          8.75
18    19                                    One Piece          8.73
19    20                            Violet Evergarden          8.68
20    21                                Made in Abyss          8.67
21    22                            Your Lie in April          8.65
22    23                                   Death Note          8.62
23    24                       Haikyu!! Second Season          8.62
24    25                                 Spy x Family          8.62
25    26                       Cyberpunk: Edgerunners          8.60
26    27                                   Oshi no Ko          8.58
27    28                              Attack on Titan          8.55
28    29                               Jujutsu Kaisen          8.55
29    30                                     Dandadan          8.55
30    31                               Mob Psycho 100          8.52
31    32                                One Punch Man          8.51
32    33                                 Chainsaw Man          8.45
33    34               Demon Slayer: Kimetsu no Yaiba          8.42
34    35                      Neon Genesis Evangelion          8.36
35    36                                  Psycho-Pass          8.32
36    37                          Parasyte: The Maxim          8.31
37    38                            Naruto: Shippuden          8.28
38    39                                    Fate/Zero          8.28
39    40                                       Erased          8.26
40    41                                    Dr. Stone          8.26
41    42       Re:Zero Starting Life in Another World          8.24
42    43                                Solo Leveling          8.20
43    44                                 Black Clover          8.14
44    45                                    Toradora!          8.07
45    46                                 Angel Beats!          8.05
46    47                             My Hero Academia          7.90
47    48                                  Tokyo Ghoul          7.79
48    49                                   Fairy Tail          7.62
49    50                             Sword Art Online          7.20>

In [141]:
data.columns

Index(['Rank', 'Title', 'Score/Rating'], dtype='str')

In [145]:
data.loc[1]['Title']

'Fullmetal Alchemist: Brotherhood'

In [146]:
!kaggleHub

'kaggleHub' is not recognized as an internal or external command,
operable program or batch file.

In [161]:
import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("muhammadaqeelkabir/top-anime-csv")

print("Path to dataset files:", path)

files = os.listdir(path)

file_path = os.path.join(path,'anime.csv')

Path to dataset files: C:\Users\Agam\.cache\kagglehub\datasets\muhammadaqeelkabir\top-anime-csv\versions\1

In [162]:
df = pd.read_csv('file_path')

FileNotFoundError: [Errno 2] No such file or directory: 'file_path'