## move with pandas

In [3]:
import numpy as np 
import pandas as pd

In [14]:
labels = ['a','b','c']
my_list =[10,20,30]
arr = np.array([10,20,30])
d = {'a':10,2:20,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(my_list,index=d)

1    10
2    20
3    30
dtype: int64

In [15]:
pd.Series(d)

a    10
2    20
3    30
dtype: int64

### Data Frame

In [20]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age':[45,56,25,65,33],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [70000, 85000, 62000, 95000, 78000]
}
index = ['a','b','c','d','e']
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
 'Age': [45, 56, 25, 65, 33],
 'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
 'Salary': [70000, 85000, 62000, 95000, 78000]}

In [25]:
df = pd.DataFrame(data,index=index)

In [27]:
df

      Name  Age      City  Salary
a    Alice   45  New York   70000
b      Bob   56    London   85000
c  Charlie   25     Paris   62000
d    David   65     Tokyo   95000
e      Eva   33    Sydney   78000

In [ ]:
pd

In [36]:
people_list = [
    # [Name, Age, City, Salary]
    ['Alice', 25, 'New York', 70000],
    ['Bob', 30, 'London', 85000],
    ['Charlie', 35, 'Paris', 95000],
    ['David', 40, 'Tokyo', 110000],
    ['Eva', 28, 'Sydney', 78000]
]

coloum_list = ["Name","Age","City","Salary"]
df2 =pd.DataFrame(people_list,columns=coloum_list )
print(df2)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30    London   85000
2  Charlie   35     Paris   95000
3    David   40     Tokyo  110000
4      Eva   28    Sydney   78000

In [37]:
df2['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str

In [39]:
df2[['Name',"City"]]

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo
4      Eva    Sydney

In [ ]:
df2['Designation']= ["Doctor","Engineer","Barber","Salesman","IAS"]
df2 = df2.drop("Designation",axis=1)

      Name  Age      City  Salary Designation
0    Alice   25  New York   70000      Doctor
1      Bob   30    London   85000    Engineer
2  Charlie   35     Paris   95000      Barber
3    David   40     Tokyo  110000    Salesman
4      Eva   28    Sydney   78000         IAS